Remove hardcoded dependencies from examples.
woocommerce/woocommerce-admin pull request #6542
Opened 2021-03-09 11:16 UTC by leewillis77

Following on from #6482, it was identified that the code examples under [`docs/examples/extensions`](https://github.com/woocommerce/woocommerce-admin/tree/main/docs/examples/extensions) all hardcode the Javascript dependencies, which is suboptimal, and can lead to odd bugs due to missing dependencies. 

This PR:

- Adds the WooCommerce Dependency Extraction webpack plugin
- Uses it during the build for `npm run example`
- Updates examples to use the generated `foo.asset.php` files rather than hardcoding dependencies

I'm not a webpack guru, so please check that everything in that section of the PR has been done sensibly. 

Also of note is that I had to add two sets of PHPCS exclusions relating to lack of nonce checks in `/sql-modification/woocommerce-admin-sql-modification.php` to be able to commit the asset file changes - although this seems to be a pre-existing issue unrelated to this PR.

2021-03-15 22:23 UTC, samueljseay commented on docs/examples/extensions/add-navigation-items/woocommerce-admin-add-navigation-items-example.php
> +	$asset_file = require __DIR__ . '/dist/index.asset.php';
👍

2021-03-15 22:26 UTC, samueljseay commented on package.json
> +		"@woocommerce/dependency-extraction-webpack-plugin": "^1.4.0",
🤔 this package is one of ours, thats in `packages`. I'm not sure we need to list this dependency, but if we did we should perhaps reference the in-repo package like we have with others.

```suggestion
		"@woocommerce/dependency-extraction-webpack-plugin": "file:packages/dependency-extraction-webpack-plugin",
```

2021-03-15 22:26 UTC, samueljseay requested changes
Thank you so much for doing this work, it looks excellent, Just one little suggested change from me.

2021-03-16 10:50 UTC, leewillis77 commented
Updated - thanks!

2021-03-17 03:19 UTC, psealock approved these changes
This is great, thank you @leewillis77 !

2021-03-17 03:21 UTC, psealock commented
I approved, but I think @samueljseay will need to as well because there are changes requested.

2021-03-17 03:33 UTC, samueljseay approved these changes
Thanks again for this! 🚀

2021-03-23 22:10 UTC, merged