Introduce a filter for extending the user's WooCommerce meta fields
woocommerce/woocommerce-admin pull request #6889
Opened 2021-04-27 12:45 UTC by xristos3490

Fixes #6888 

For description please check the issue details.

### Changelog entry
```
Tweak: Introduced the `woocommerce_user_data_fields` filter for extending the user's WooCommerce meta fields.
```

_Note: Package changelog updated as well_

2021-04-27 20:28 UTC, jeffstieler requested changes
Hi @xristos3490,

Thank you for highlighting this issue and submitting a PR!

Rather than adding a filter, I think we should just remove the allowlist functionality. It seems to have little value if the list is filterable anyhow.

If you're not comfortable making those changes let me know and I'll take care of it.

Thanks again.

2021-04-28 12:11 UTC, xristos3490 commented
Hey @jeffstieler,

> It seems to have little value if the list is filterable anyhow.

Agreed! Taking a look at the additional user schema for "woocommerce_meta" added by the `Loader::register_user_data()` it seems that the validity of the individual meta keys are also checked in PHP. 
See:
https://github.com/woocommerce/woocommerce-admin/blob/a437d32d22d582fdbc03250e3a117caeb760b891/src/Loader.php#L1251

With that said, there is no way to "spam" with meta keys without first declaring them through the `woocommerce_admin_get_user_data_fields` filter.

Moreover, updating a filter for the "_Allowlist_" in both places should be hard to maintain and therefore removing this filter should keep our data in a **single source of truth**.

2021-04-28 14:37 UTC, jeffstieler requested changes
This is testing well, but the linters aren't happy. 😅 

Can you add the change log entry (I pointed out where inline), and fix the code formatting issues?

* Remove the unused `pick` import
* Change the `mapValues()` call to be a single line

You can run the linters locally using `npm run lint:js`.

2021-04-28 14:37 UTC, jeffstieler commented on packages/data/CHANGELOG.md
> +-   Removed allowed keys list for adding woocommerce_meta data. #6889
Can you add this line to `readme.txt` under the `== Unreleased ==` header? That will stop the linter from failing.

Like:
`- Dev: Removed allowed keys list for adding woocommerce_meta data. #6889`

2021-04-28 21:37 UTC, jeffstieler approved these changes
Nice work, thank you for the contribution!

2021-04-28 22:18 UTC, merged