AdvancedFilters: Create workable defaults for Reports that don't have them
woocommerce/woocommerce-admin pull request #7186
Opened 2021-06-15 04:26 UTC by psealock

Fixes #

_Replace this with a good description of your changes & reasoning._

### Accessibility

-   [ ] I've tested using only a keyboard (no mouse)
-   [ ] I've tested using a screen reader
-   [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
-   [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

### Screenshots

### Detailed test instructions:

-   Ex: Open page `url`
-   Click XYZ…

2021-06-16 17:58 UTC, jeffstieler reviewed
This code looks good and tests well, but were the Products and Revenue reports missed?

2021-06-18 04:10 UTC, psealock commented
Products and Revenue added, this is ready for another look

2021-06-18 13:27 UTC, jeffstieler requested changes
There's a bug with the Revenue report filter config, and some copy-pasta that needs cleaning up. 🍝

2021-06-18 13:27 UTC, jeffstieler commented on client/analytics/report/categories/config.js
> +			'A sentence describing filters for Variations. See screen shot for context: https://cloudup.com/cSsUY9VeCVJ',
Variations should be Categories.

2021-06-18 13:27 UTC, jeffstieler commented on client/analytics/report/coupons/config.js
> +			'A sentence describing filters for Variations. See screen shot for context: https://cloudup.com/cSsUY9VeCVJ',
Variations should be Coupons.

2021-06-18 13:27 UTC, jeffstieler commented on client/analytics/report/products/config.js
> +			'A sentence describing filters for Variations. See screen shot for context: https://cloudup.com/cSsUY9VeCVJ',
Variations should be Products.

2021-06-18 13:27 UTC, jeffstieler commented on client/analytics/report/products/config.js
> +			'Product Match {{select /}} Filters',
Should product be pluralized here?

2021-06-18 13:27 UTC, jeffstieler commented on client/analytics/report/revenue/config.js
> +	filterValues
This isn't a complete config and results in the following console error: `An error occurred while running 'mapSelect': filterConfig.showFilters is not a function`.

2021-06-18 13:27 UTC, jeffstieler commented on client/analytics/report/revenue/config.js
> +			'A sentence describing filters for Variations. See screen shot for context: https://cloudup.com/cSsUY9VeCVJ',
Variations should be Revenue.

2021-06-18 13:27 UTC, jeffstieler commented on client/analytics/report/revenue/config.js
> +			'Revenue Match {{select /}} Filters',
Should this be "Revenue Matches"?

2021-06-18 13:27 UTC, jeffstieler commented on client/analytics/report/stock/config.js
> +			'A sentence describing filters for Variations. See screen shot for context: https://cloudup.com/cSsUY9VeCVJ',
Variations should be Products.

2021-06-18 13:27 UTC, jeffstieler commented on client/analytics/report/stock/config.js
> +			'Taxes Match {{select /}} Filters',
Should this be Products?

2021-06-18 13:27 UTC, jeffstieler commented on client/analytics/report/taxes/config.js
> +			'A sentence describing filters for Variations. See screen shot for context: https://cloudup.com/cSsUY9VeCVJ',
Variations should be Taxes.

2021-06-23 10:43 UTC, psealock commented
Note to self: This should be a better default

https://github.com/woocommerce/woocommerce-admin/blob/130eb95bae34a8efd83143c52cc08864efc15131/packages/components/src/filters/index.js#L225

2021-07-08 03:57 UTC, psealock commented
Thanks for the review @jeffstieler.

I fixed the strings, addressed the Revenue Report problem you found and found another error in Stock Report. The filters modify a query param `type`, not `filter`, so if any advancedFilters have been added a new set of filters gets added.

This is ready for another look 🙇🏽‍♂️

2021-07-13 14:31 UTC, jeffstieler approved these changes
Code looks good and this is testing well. 🛳️   it!

2021-07-13 22:11 UTC, psealock commented
Since this will be cherry-picked, changelog was added as part of https://github.com/woocommerce/woocommerce-admin/pull/7320

2021-07-13 22:17 UTC, merged